version: '3'

services:
  docs:
    image: spacey_backend_internship_assignment_local_docs
    container_name: spacey_backend_internship_assignment_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./spacey_backend_internship_assignment:/app/spacey_backend_internship_assignment:z
    ports:
      - '9000:9000'
    command: /start-docs
